"""
Hatch patterns for publiplots.

This module provides configurable hatch patterns for distinguishing categories
in publication-ready visualizations. Hatch patterns are particularly useful for
black-and-white printing or when color alone is insufficient to distinguish groups.

The module supports three density modes for patterns:
    - Mode 1: Simple, sparse patterns (recommended for most use cases)
    - Mode 2: Medium-density patterns (for higher contrast needs)
    - Mode 3: Dense patterns (for maximum distinction or small plot areas)
"""

from typing import Optional, Dict, List, Set, Union

from publiplots.themes.rcparams import rcParams


# =============================================================================
# Base Hatch Patterns (Mode 1)
# =============================================================================

BASE_HATCH_PATTERNS: List[str] = [
    "",     # No hatch
    "/",    # Diagonal lines (forward)
    "\\",   # Diagonal lines (backward)
    ".",    # Dots
    "|",    # Vertical lines
    "-",    # Horizontal lines
    "+",    # Plus signs
    "x",    # Crosses
]
_ALLOWED_HATCH_MODES: Set[int] = {1, 2, 3, 4}

"""
Base hatch patterns (simple single-character patterns).

These are the fundamental pattern units that get multiplied to create
denser patterns based on the selected mode. The actual patterns used
in plots are generated by multiplying these base patterns:
    - Mode 1: base × 1 (e.g., '/', '.' → '/', '.')
    - Mode 2: base × 2 (e.g., '/', '.' → '//', '..')
    - Mode 3: base × 3 (e.g., '/', '.' → '///', '...')
    - Mode 4: base × 4 (e.g., '/', '.' → '////', '....')

Example:
    >>> import publiplots as pp
    >>> pp.set_hatch_mode(1)
    >>> ax = pp.barplot(data=df, x='x', y='y', hue='category')
"""


# =============================================================================
# Pattern Generation Functions
# =============================================================================

def _generate_denser_pattern(base_pattern: str, multiplier: int) -> str:
    """
    Generate a denser version of a pattern by multiplying its elements.

    For patterns with repeated characters, this increases density by
    repeating the base unit multiple times. Empty patterns remain empty.

    Parameters
    ----------
    base_pattern : str
        The base pattern string to densify.
    multiplier : int
        How many times to repeat the pattern elements (typically 2 or 3).

    Returns
    -------
    str
        The densified pattern string.

    Examples
    --------
    >>> _generate_denser_pattern('///', 2)
    '//////'
    >>> _generate_denser_pattern('...', 3)
    '.........'
    >>> _generate_denser_pattern('', 2)
    ''
    """
    if not base_pattern:
        return base_pattern
    return (base_pattern * multiplier).strip()


def get_hatch_patterns(mode: Optional[int] = None) -> List[str]:
    """
    Get hatch patterns for a specified density mode.

    The density mode controls how dense / sparse the hatch patterns are
    by multiplying the base patterns:

    - Mode 1: base × 1 (e.g., ``'/'``, ``'.'`` becomes ``'/'``, ``'.'``).
    - Mode 2: base × 2 (e.g., ``'/'``, ``'.'`` becomes ``'//'``, ``'..'``).
    - Mode 3: base × 3 (e.g., ``'/'``, ``'.'`` becomes ``'///'``, ``'...'``).
    - Mode 4: base × 4 (e.g., ``'/'``, ``'.'`` becomes ``'////'``, ``'....'``).

    Denser patterns provide stronger visual distinction but may appear
    cluttered in small plot areas. Mode 1 is recommended for most use
    cases.

    Parameters
    ----------
    mode : int, optional
        Pattern density mode. Must be ``1``, ``2``, ``3``, or ``4``.
        If ``None``, uses the current global mode from
        ``pp.rcParams["hatch_mode"]``.

    Returns
    -------
    list of str
        Hatch pattern strings of the requested density.

    Raises
    ------
    ValueError
        If ``mode`` is not ``1``, ``2``, ``3``, or ``4``.

    Examples
    --------
    Get mode 1 patterns:

    >>> import publiplots as pp
    >>> patterns = pp.get_hatch_patterns(mode=1)
    >>> patterns[1]
    '/'

    Get mode 3 (dense) patterns:

    >>> patterns = pp.get_hatch_patterns(mode=3)
    >>> patterns[1]
    '///'

    Use the current global mode:

    >>> pp.set_hatch_mode(2)
    >>> patterns = pp.get_hatch_patterns()  # Uses mode 2

    See Also
    --------
    set_hatch_mode : Set the global hatch density mode.
    get_hatch_mode : Read the current global hatch density mode.
    resolve_hatches : Produce a cycled list of patterns for N categories.
    """
    # Get the mode to use
    if mode is None:
        mode = get_hatch_mode()

    # Validate mode
    if mode not in _ALLOWED_HATCH_MODES:
        raise ValueError(
            f"Invalid hatch mode {mode}. Mode must be 1, 2, 3, or 4. "
            "Use set_hatch_mode() to change the global mode."
        )

    # Generate patterns by multiplying base patterns
    return [_generate_denser_pattern(pattern, mode) for pattern in BASE_HATCH_PATTERNS]


def set_hatch_mode(mode: Optional[int] = None) -> None:
    """
    Set the global hatch pattern density mode.

    This setting affects all subsequent hatch pattern generation unless
    explicitly overridden. The mode determines the density of hatch
    patterns:

    - Mode 1: base × 1 patterns (e.g., ``'/'``, ``'.'``) — sparse.
    - Mode 2: base × 2 patterns (e.g., ``'//'``, ``'..'``) — medium.
    - Mode 3: base × 3 patterns (e.g., ``'///'``, ``'...'``) — dense.
    - Mode 4: base × 4 patterns (e.g., ``'////'``, ``'....'``) — very dense.

    Writes to ``pp.rcParams["hatch_mode"]``.

    Parameters
    ----------
    mode : int, optional
        Pattern density mode. Must be ``1``, ``2``, ``3``, or ``4``.
        If ``None``, resets to the package default (``1``).

    Raises
    ------
    ValueError
        If ``mode`` is not ``None``, ``1``, ``2``, ``3``, or ``4``.

    Examples
    --------
    Set to sparse patterns (mode 1):

    >>> import publiplots as pp
    >>> pp.set_hatch_mode(1)
    >>> fig, ax = pp.subplots()
    >>> pp.barplot(data=df, x='x', y='y', hue='category', hatch=True, ax=ax)

    Set to dense patterns:

    >>> pp.set_hatch_mode(3)

    Reset to default mode:

    >>> pp.set_hatch_mode()  # or pp.set_hatch_mode(None)
    >>> pp.get_hatch_mode()
    1

    Notes
    -----
    This is a global setting that persists across function calls
    within the same session. To revert, call ``set_hatch_mode()`` with
    no arguments (or ``None``).

    See Also
    --------
    get_hatch_mode : Read the current mode.
    get_hatch_patterns : Materialise the pattern list for a mode.
    """
    # Handle reset to default
    if mode is None:
        # Reset to default value from PUBLIPLOTS_RCPARAMS
        mode = 1

    # Validate mode
    if mode not in _ALLOWED_HATCH_MODES:
        raise ValueError(
            f"Invalid hatch mode {mode}. Mode must be 1 (sparse), "
            "2 (medium), 3 (dense), or 4 (very dense), or None to reset to default."
        )

    # Set via rcParams
    rcParams['hatch_mode'] = mode


def get_hatch_mode() -> int:
    """
    Get the current global hatch pattern density mode.

    Reads ``pp.rcParams["hatch_mode"]``; returns the package default
    (``1``) if no other mode has been set.

    Returns
    -------
    int
        Current hatch mode (one of ``1``, ``2``, ``3``, ``4``).

    Examples
    --------
    Check the current mode:

    >>> import publiplots as pp
    >>> pp.get_hatch_mode()
    1

    Change and verify the mode:

    >>> pp.set_hatch_mode(3)
    >>> pp.get_hatch_mode()
    3

    Reset to the default:

    >>> pp.set_hatch_mode()
    >>> pp.get_hatch_mode()
    1

    See Also
    --------
    set_hatch_mode : Set or reset the global hatch mode.
    get_hatch_patterns : Get patterns for a specific mode.
    """
    return rcParams['hatch_mode']


# =============================================================================
# Pattern Resolution Functions
# =============================================================================

def resolve_hatches(
    hatches: Optional[List[str]] = None,
    n_hatches: Optional[int] = None,
    reverse: bool = False,
    mode: Optional[int] = None
) -> List[str]:
    """
    Resolve hatch patterns for plotting.

    Helper that standardises hatch pattern specifications into a
    concrete list. Handles pattern cycling for arbitrary category
    counts and supports reversal.

    Parameters
    ----------
    hatches : list of str, optional
        Hatch patterns to use. If ``None``, pulls patterns from
        :func:`get_hatch_patterns` at the current or specified mode.
    n_hatches : int, optional
        Number of patterns to return. If provided, the source list is
        cycled to reach this count. If ``None``, returns the full
        source list.
    reverse : bool, default ``False``
        Whether to reverse the final pattern order. Useful for matching
        a reversed color palette.
    mode : int, optional
        Pattern density mode (``1``, ``2``, ``3``, or ``4``). If
        ``None``, uses the current global mode. Only applicable when
        ``hatches`` is ``None``.

    Returns
    -------
    list of str
        Resolved hatch pattern strings.

    Examples
    --------
    Get default patterns:

    >>> import publiplots as pp
    >>> patterns = pp.resolve_hatches()
    >>> len(patterns)
    8

    Get exactly 5 patterns with cycling:

    >>> patterns = pp.resolve_hatches(n_hatches=5)
    >>> len(patterns)
    5

    Use custom patterns:

    >>> patterns = pp.resolve_hatches(hatches=['///', '|||', 'xxx'], n_hatches=7)

    Get reversed patterns:

    >>> patterns = pp.resolve_hatches(n_hatches=4, reverse=True)

    Use a specific density mode:

    >>> patterns = pp.resolve_hatches(mode=3, n_hatches=5)

    See Also
    --------
    resolve_hatch_map : Create a mapping from values to patterns.
    get_hatch_patterns : Get patterns for a specific mode.
    set_hatch_mode : Set the global hatch density mode.
    """
    # Get default patterns if not provided
    if hatches is None:
        hatches = get_hatch_patterns(mode=mode)

    # Cycle patterns if n_hatches specified
    if n_hatches is not None:
        hatches = [hatches[i % len(hatches)] for i in range(n_hatches)]

    # Reverse if requested
    if reverse:
        hatches = hatches[::-1]

    return hatches


def resolve_hatch_map(
    values: Optional[List[str]] = None,
    hatch_map: Optional[Union[Dict[str, str], List[str]]] = None,
    reverse: bool = False,
    mode: Optional[int] = None
) -> Dict[str, str]:
    """
    Create a mapping from category values to hatch patterns.

    Returns a dictionary that maps category names to specific hatch
    patterns, useful for categorical plots like
    :func:`publiplots.barplot` with ``hatch=True``. Ensures consistent
    pattern assignment across multiple plots.

    Parameters
    ----------
    values : list of str, optional
        Category values to map to patterns. If ``None``, returns an
        empty dict.
    hatch_map : dict or list of str, optional
        Hatch pattern specification:

        - ``dict`` — explicit mapping from values to patterns;
          returned as-is.
        - ``list`` — patterns cycled through the ``values`` list.
        - ``None`` — defaults to :func:`get_hatch_patterns` at the
          current mode.
    reverse : bool, default ``False``
        Whether to reverse the pattern assignment order. Only
        applicable when ``hatch_map`` is a list or ``None``.
    mode : int, optional
        Pattern density mode (``1``, ``2``, ``3``, or ``4``). If
        ``None``, uses the current global mode. Only applicable when
        ``hatch_map`` is ``None``.

    Returns
    -------
    dict of {str: str}
        Mapping from category values to hatch pattern strings.

    Examples
    --------
    Create a mapping for categories at mode 1:

    >>> import publiplots as pp
    >>> mapping = pp.resolve_hatch_map(values=['A', 'B', 'C', 'D'], mode=1)
    >>> mapping['A']
    ''
    >>> mapping['B']
    '/'

    Use custom patterns cycled through values:

    >>> mapping = pp.resolve_hatch_map(
    ...     values=['cat', 'dog', 'bird'],
    ...     hatch_map=['///', '|||', 'xxx'],
    ... )

    Pass an explicit mapping (returned unchanged):

    >>> mapping = pp.resolve_hatch_map(
    ...     values=['A', 'B'],
    ...     hatch_map={'A': '///', 'B': '|||'},
    ... )
    >>> mapping
    {'A': '///', 'B': '|||'}

    Use dense patterns:

    >>> mapping = pp.resolve_hatch_map(values=['A', 'B', 'C'], mode=3)

    See Also
    --------
    resolve_hatches : Resolve patterns without creating a mapping.
    get_hatch_patterns : Get patterns for a specific mode.
    """
    # Return empty dict if no values provided
    if values is None:
        return {}

    # If already a dict, return as-is
    if isinstance(hatch_map, dict):
        return hatch_map

    # Resolve patterns and create mapping
    hatches = resolve_hatches(
        hatches=hatch_map,
        n_hatches=len(values),
        reverse=reverse,
        mode=mode
    )

    return {value: hatch for value, hatch in zip(values, hatches)}


# =============================================================================
# Legacy Compatibility
# =============================================================================

# For backward compatibility, maintain HATCH_PATTERNS as the base patterns
HATCH_PATTERNS: List[str] = BASE_HATCH_PATTERNS
"""
Legacy constant for backward compatibility.

This contains the simple single-character base patterns (e.g., '/', '\', '.').
These are NOT the patterns used in plots - actual plot patterns are generated
by multiplying these base patterns according to the mode setting.

For new code, use get_hatch_patterns() which respects the current hatch mode
setting and returns the actual patterns used in plots.

Deprecated: Use get_hatch_patterns() instead for mode-aware pattern selection.
"""


# =============================================================================
# Utility Functions
# =============================================================================

def list_hatch_patterns(mode: Optional[int] = None) -> None:
    """
    Print available hatch patterns for visual inspection.

    Displays all available hatch patterns at the specified mode —
    useful for choosing appropriate patterns for your plots.

    Parameters
    ----------
    mode : int, optional
        Pattern density mode (``1``, ``2``, ``3``, or ``4``). If
        ``None``, uses the current global mode.

    Examples
    --------
    List current mode patterns::

        >>> import publiplots as pp
        >>> pp.list_hatch_patterns(mode=1)
        Hatch Patterns (Mode 1):
          0: '' (no hatch)
          1: '/'
          2: '\\'
          3: '.'
          4: '|'

    List a specific mode::

        >>> pp.list_hatch_patterns(mode=4)
        Hatch Patterns (Mode 4):
          0: '' (no hatch)
          1: '////'
          ...

    See Also
    --------
    get_hatch_patterns : Return the list of patterns (without printing).
    """
    if mode is None:
        mode = get_hatch_mode()

    patterns = get_hatch_patterns(mode=mode)

    print(f"Hatch Patterns (Mode {mode}):")
    for i, pattern in enumerate(patterns):
        if pattern == "":
            print(f"  {i}: '' (no hatch)")
        else:
            print(f"  {i}: '{pattern}'")
